import { GetStaticProps, NextPageWithLayout } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { ArticleListItem } from '@/components/article-list-item';
import BaseLayout from '@/components/base-layout';
import { Title } from '@/components/title';
import { ArticleItem } from '@/features/article/article.schema';
import { articleService } from '@/features/article/article.service';

interface HomePageProps {
  articles: ArticleItem[];
}

const Home: NextPageWithLayout<HomePageProps> = ({ articles }) => {
  return (
    <>
      <Title />
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <h2 className="text-5xl mb-2">
            Hello,
            <br />
            I&apos;m Nicolas,
            <br />
            software developer.
          </h2>
          <p className="text-xl">Focusing on Node.js and React.</p>
        </div>
        <h2>
          <Link href="/blog" className="no-underline hover:underline">
            Blog
          </Link>
        </h2>
        <hr className="mt-0" />
        <ul>
          {articles.map((article) => (
            <li key={article.slug}>
              <ArticleListItem article={article} />
            </li>
          ))}
        </ul>
      </div>
    </>
  );
};

Home.getLayout = (component) => {
  return <BaseLayout>{component}</BaseLayout>;
};

export const getStaticProps: GetStaticProps<HomePageProps> = async () => {
  const articles = await articleService.getArticles();

  return {
    props: {
      articles,
    },
  };
};

export default Home;
