import { GetStaticProps, NextPageWithLayout } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { ArticleListItem } from '@/components/article-list-item';
import BaseLayout from '@/components/base-layout';
import { Title } from '@/components/title';
import { ArticleItem, getArticles } from '@/lib/mdx/article';

interface HomePageProps {
  articles: ArticleItem[];
}

const Home: NextPageWithLayout<HomePageProps> = ({ articles }) => {
  return (
    <>
      <Title />
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <h2>Hi.</h2>
          <p>
            I&apos;m Nicolas - currently working as a full-stack developer. I
            make use of technologies such as NodeJS, React, Vue, and MySQL,
            among others, to build full stack applications. I created this blog
            to share some of the things I&apos;ve learned along the way.
          </p>
        </div>
        <h2>
          <Link href="/blog" className="no-underline hover:underline">
            Blog
          </Link>
        </h2>
        <hr className="mt-0" />
        <ul>
          {articles.map((article) => (
            <li key={article.slug}>
              <ArticleListItem article={article} />
            </li>
          ))}
        </ul>
      </div>
    </>
  );
};

Home.getLayout = (component) => {
  return <BaseLayout>{component}</BaseLayout>;
};

export const getStaticProps: GetStaticProps<HomePageProps> = async () => {
  const articles = await getArticles();

  return {
    props: {
      articles,
    },
  };
};

export default Home;
