import { GetStaticProps, NextPage, NextPageWithLayout } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { ArticleListItem } from '@/components/article-list-item';
import BaseLayout from '@/components/base-layout';
import { Title } from '@/components/title';
import { ArticleItem } from '@/features/article/article.schema';
import { articleService } from '@/features/article/article.service';

interface HomePageProps {
  articles: ArticleItem[];
}

const Home = async () => {
  const articles = await articleService.getArticles();
  return (
    <>
      <Title />
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>
          <Link href="/blog" className="no-underline hover:underline">
            Blog
          </Link>
        </h2>
        <hr className="mt-0" />
        <ul>
          {articles.map((article) => (
            <li key={article.slug}>
              <ArticleListItem article={article} />
            </li>
          ))}
        </ul>
      </div>
    </>
  );
};

export const metadata = {
  title: 'Home | vitaterna.ca',
};

export default Home;
